# Generated by Django 4.1.5 on 2023-01-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_contact_contactformsubmission"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_source", models.CharField(max_length=200)),
                ("screen_height", models.IntegerField(blank=True, null=True)),
                ("screen_width", models.IntegerField(blank=True, null=True)),
                ("browser_type", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=100)),
                ("time_zone", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
