# Generated by Django 4.1.5 on 2023-01-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactformsubmission",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teammember",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
